/* Every text of the solar panel, one object per language. Loaded by solar-view.js.
   A string must not contain a double quote, <, > or &: some go into HTML attributes.
   Every language needs every key that `en` has. Each advice pool needs the same number of
   lines as in `en`, in the same order, each line meaning the same as the English one. */

export const STRINGS = {
  en: {
    pages: "Pages",
    tabNow: "Now", tabToday: "Today", tabHistory: "Past days", tabDetails: "Info",
    until: "Powering the house, enough until about {t}",
    untilSun: "Powering the house, enough until the sun takes over",
    saved: "About {v} saved today", savedNone: "Nothing saved yet today", earned: "{v} earned by selling",
    ySaved: "saved", savedLabel: "Saved",
    sunUse: "Sun use today", usedAtHome: "Sun used at home", homeMadeShare: "House use that was home made",
    battMonth: "Battery", roundTrip: "Given back last month", cycles: "Full cycles last month",
    battIn: "Battery charged", battOut: "Battery gave",
    forecast: "Forecast", fToday: "Forecast for today", fSoFar: "Made so far", fTomorrow: "Forecast for tomorrow",
    noForecast: "No solar forecast is linked in the Energy settings",
    monthNumbers: "Month in numbers", colThis: "this", colLast: "last",
    prices: "Prices", buy: "Bought, per kWh", sell: "Sold, per kWh", notSet: "not set",
    runOn: "The house is running on {a}",
    and: "{a} and {b}",
    src: { sun: "the sun", battery: "the battery", grid: "the grid" },
    subGrid: "The grid is lending a hand",
    subExport: "The extra sun is going to the grid",
    subCharge: "The extra sun is filling the battery",
    subBattery: "The battery is giving back the sun it saved",
    sun: "Sun", noSun: "No sun", battery: "Battery", home: "Home", grid: "Grid",
    empty: "Empty", low: "Low", good: "Good", nearlyFull: "Almost full", full: "Full",
    noUseYet: "The house has not used anything yet today",
    charging: "Filling up with sun", discharging: "Powering the house", resting: "Resting",
    adviceTitle: "Advice",
    // Advice: a pool of lines per situation, one is shown per day (see advicePool). Same order in
    // every language. Each line must stay true to its situation and fit two lines on a phone.
    adviceGo: [ // spare sun right now
      "Good moment to run the washing machine or dishwasher",
      "Plenty of sun: a good time to put the oven on",
      "There is sun left over: on with the dishwasher",
      "The sun is feeling generous: good time to iron",
      "Sun to spare: a fine moment for the vacuum cleaner",
      "More sun than the house needs: laundry time",
      "Sunshine going spare: charge the phones and tablets",
      "Lots of sun right now: a good time for the dryer",
      "The sun is paying: run the big appliances now",
      "Spare sun on the roof: time to bake something?",
    ],
    adviceGoFull: [ // spare sun and the battery is nearly or fully charged
      "Battery full and sun to spare: use it freely",
      "Nowhere left to store the sun: run something big",
      "Full battery, full sun: washing machine time",
      "The battery is full, the rest is a gift: use it",
    ],
    adviceLow: [ // battery low and no sun
      "Battery is low, big appliances will use the grid",
      "Battery nearly empty: best keep the big appliances for later",
      "Low battery and no sun: the washing can wait",
      "Battery running low: go easy until the sun is back",
      "Little left in the battery: big jobs can wait",
    ],
    adviceEmpty: [ // battery at 0 and no sun
      "Battery empty: the house is on the grid for now",
      "Nothing left in the battery, the sun will refill it",
      "Empty battery: best wait for the sun for big jobs",
    ],
    adviceWait: [ // poor sun today, clearly better forecast tomorrow
      "Little sun today, more tomorrow: best wash tomorrow",
      "Lazy sun today, busier tomorrow: the laundry can wait",
      "Tomorrow brings more sun: save the big washes for then",
      "Grey today, brighter tomorrow: washing can wait",
      "Not much sun today. Laundry day is tomorrow",
    ],
    adviceOk: [ // nothing to do, sun above the horizon
      "All good, nothing to do",
      "All quiet here. Time for a coffee?",
      "Nothing to do, the house is looking after itself",
      "Everything is running smoothly, carry on",
      "The sun is up and the house is ticking along",
      "Nothing needs doing right now, enjoy your day",
      "Nothing to report, and that is good news",
      "The house is fine. You can relax",
      "All in order here, nothing for you to do",
      "Calm seas at home, no help needed",
      "The house is humming along nicely",
      "No news is good news: all fine here",
    ],
    adviceOkNight: [ // nothing to do, sun below the horizon
      "The sun is off duty, the house carries on by itself",
      "The sun has gone to bed, all is well here",
      "All good, even the sun is having a rest",
      "Quiet night, the house has all it needs",
      "Nothing to do tonight, enjoy your evening",
      "All calm here. See you with the sun",
      "Good night from the house, all is well",
      "Nothing to do until the sun comes back",
    ],
    adviceOkFull: [ // nothing to do and the battery is nearly or fully charged
      "Battery nicely full, nothing to do",
      "Plenty in the battery: a calm day ahead",
      "The battery is topped up and all is well",
      "Full of energy here. How about you?",
    ],
    adviceOkRefill: [ // battery low, but the sun is charging it
      "Battery is low, but the sun is already on it",
      "The sun is refilling the battery, just give it time",
      "Low battery, sun at work: nothing for you to do",
    ],
    shareToday: "of today's power was home made",
    todayNumbers: "Today in numbers",
    made: "The sun made", used: "The house used", takenBatt: "Taken from the battery", taken: "Taken from the grid", sent: "Sent to the grid",
    nothing: "nothing", almostNothing: "almost nothing",
    yesterday: "Yesterday", homeMade: "home made",
    ySun: "sun", yHouse: "house", yGrid: "grid", ySent: "sent",
    week: "Sun in the last 7 days",
    monthTitle: "This month and last month",
    thisMonth: "This month so far", lastMonth: "Last month",
    more: "More sun per day than last month",
    less: "A little less sun per day than last month",
    same: "About the same sun as last month",
    loading: "Loading...",
    hSun: "The panels are making {w} W right now. {k} so far today.",
    hSunOff: "No sun right now. {k} made today.",
    hHome: "The house is using {w} W right now. {k} so far today.",
    hBattIn: "Battery at {p} %, filling up at {w} W.",
    hBattOut: "Battery at {p} %, giving {w} W to the house.",
    hBattIdle: "Battery at {p} %, resting.",
    hGridIn: "Taking {w} W from the grid right now. {k} so far today.",
    hGridOut: "Sending {w} W to the grid right now. {k} so far today.",
    hGridIdle: "Not using the grid right now. {k} taken today.",
    hDay: "{d}: the sun made {k}",
    hShare: "{a} of the {b} used today came from our own sun and battery",
    hGauge: "About {a} in the battery, out of {b}",
    offline: "The inverter is not answering right now. The numbers will come back by themselves.",
    setup: "Nothing to show yet. In Home Assistant, open Settings, Dashboards, Energy and add the solar panels with their power sensor.",
    missing: "Not found:",
  },
  it: {
    pages: "Pagine",
    tabNow: "Adesso", tabToday: "Oggi", tabHistory: "Giorni scorsi", tabDetails: "Info",
    until: "Sta dando corrente alla casa, basta fino alle {t} circa",
    untilSun: "Sta dando corrente alla casa, basta finché non arriva il sole",
    saved: "Oggi circa {v} risparmiati", savedNone: "Oggi ancora niente risparmiato", earned: "{v} guadagnati vendendo",
    ySaved: "risparmiati", savedLabel: "Risparmiati",
    sunUse: "Uso del sole oggi", usedAtHome: "Sole usato in casa", homeMadeShare: "Consumo coperto da sole e batteria",
    battMonth: "Batteria", roundTrip: "Restituito il mese scorso", cycles: "Cicli completi il mese scorso",
    battIn: "Messa in batteria", battOut: "Presa dalla batteria",
    forecast: "Previsione", fToday: "Previsione per oggi", fSoFar: "Prodotto finora", fTomorrow: "Previsione per domani",
    noForecast: "Nessuna previsione solare collegata nelle impostazioni Energia",
    monthNumbers: "Il mese in numeri", colThis: "questo", colLast: "scorso",
    prices: "Prezzi", buy: "Comprata, al kWh", sell: "Venduta, al kWh", notSet: "non impostato",
    runOn: "Adesso la corrente viene {a}",
    and: "{a} e {b}",
    src: { sun: "dal sole", battery: "dalla batteria", grid: "dalla rete" },
    subGrid: "La rete sta dando una mano",
    subExport: "Il sole in più va alla rete",
    subCharge: "Il sole in più sta caricando la batteria",
    subBattery: "La batteria restituisce il sole messo da parte",
    sun: "Sole", noSun: "Niente sole", battery: "Batteria", home: "Casa", grid: "Rete",
    empty: "Scarica", low: "Bassa", good: "Bene", nearlyFull: "Quasi piena", full: "Piena",
    noUseYet: "Oggi la casa non ha ancora consumato niente",
    charging: "Si sta caricando con il sole", discharging: "Sta dando corrente alla casa", resting: "A riposo",
    adviceTitle: "Consiglio",
    adviceGo: [
      "Buon momento per far partire la lavatrice o la lavastoviglie",
      "Sole a volontà: buon momento per accendere il forno",
      "C'è sole che avanza: via con la lavastoviglie",
      "Il sole è generoso: buon momento per stirare",
      "Avanza del sole: è il momento dell'aspirapolvere",
      "Più sole di quanto serve alla casa: è l'ora del bucato",
      "Sole in avanzo: metti in carica telefoni e tablet",
      "Tanto sole adesso: buon momento per l'asciugatrice",
      "Offre il sole: fai andare adesso i lavori grossi",
      "Sole che avanza sul tetto: si inforna qualcosa?",
    ],
    adviceGoFull: [
      "Batteria piena e sole che avanza: usalo pure",
      "Il sole non sa più dove andare: accendi qualcosa",
      "Batteria piena, sole pieno: è l'ora della lavatrice",
      "La batteria è piena, il resto è regalato: usalo",
    ],
    adviceLow: [
      "Batteria bassa: lavatrice e forno ora userebbero la rete",
      "Batteria quasi a terra: meglio rimandare lavatrice e forno",
      "Poca batteria e niente sole: il bucato può aspettare",
      "Batteria agli sgoccioli: vacci piano fino al sole",
      "Resta poco in batteria: i lavori grossi aspettano",
    ],
    adviceEmpty: [
      "Batteria scarica: per ora la casa va con la rete",
      "Batteria vuota, ci penserà il sole a riempirla",
      "Batteria scarica: per i lavori grossi aspetta il sole",
    ],
    adviceWait: [
      "Oggi poco sole, domani va meglio: se puoi, lava domani",
      "Sole pigro oggi, domani si rifà: il bucato può aspettare",
      "Domani c'è più sole: tieni per domani i lavaggi grossi",
      "Oggi grigio, domani meglio: lavare può aspettare",
      "Oggi poco sole. Il giorno del bucato è domani",
    ],
    adviceOk: [
      "Tutto a posto, non c'è niente da fare",
      "Qui tutto tranquillo. Ci sta un caffè?",
      "Niente da fare, la casa si arrangia da sola",
      "Fila tutto liscio, continua pure così",
      "Il sole è su e la casa va avanti tranquilla",
      "Per ora non serve fare niente, goditi la giornata",
      "Niente da segnalare, ed è una bella notizia",
      "La casa sta bene. Si può stare tranquilli",
      "Qui è tutto in ordine, non devi fare niente",
      "Mare calmo in casa, non serve nessun aiuto",
      "La casa va che è una meraviglia",
      "Nessuna nuova, buona nuova: qui tutto bene",
    ],
    adviceOkNight: [
      "Il sole ha staccato, la casa va avanti da sola",
      "Il sole è andato a dormire, qui tutto bene",
      "Tutto a posto, anche il sole si riposa",
      "Notte tranquilla, la casa ha quello che le serve",
      "Stasera niente da fare, buona serata",
      "Qui tutto calmo. Ci si rivede con il sole",
      "Buonanotte dalla casa, va tutto bene",
      "Niente da fare finché non torna il sole",
    ],
    adviceOkFull: [
      "Batteria bella piena, non c'è niente da fare",
      "Batteria ben carica: giornata tranquilla",
      "La batteria è bella carica e va tutto bene",
      "Qui siamo carichi. E tu?",
    ],
    adviceOkRefill: [
      "Batteria bassa, ma il sole ci sta già pensando",
      "Il sole sta ricaricando la batteria, serve solo tempo",
      "Batteria bassa, sole al lavoro: non devi fare niente",
    ],
    shareToday: "della corrente di oggi è fatta in casa",
    todayNumbers: "Oggi in numeri",
    made: "Il sole ha prodotto", used: "La casa ha usato", takenBatt: "Presa dalla batteria", taken: "Presa dalla rete", sent: "Mandata alla rete",
    nothing: "niente", almostNothing: "quasi niente",
    yesterday: "Ieri", homeMade: "fatta in casa",
    ySun: "sole", yHouse: "casa", yGrid: "dalla rete", ySent: "alla rete",
    week: "Il sole negli ultimi 7 giorni",
    monthTitle: "Questo mese e il mese scorso",
    thisMonth: "Questo mese finora", lastMonth: "Il mese scorso",
    more: "Più sole al giorno rispetto al mese scorso",
    less: "Un po' meno sole al giorno rispetto al mese scorso",
    same: "Più o meno lo stesso sole del mese scorso",
    loading: "Caricamento...",
    hSun: "I pannelli stanno producendo {w} W adesso. {k} da stamattina.",
    hSunOff: "Adesso non c'è sole. Oggi i pannelli hanno prodotto {k}.",
    hHome: "La casa sta usando {w} W adesso. {k} da stamattina.",
    hBattIn: "Batteria al {p} %, si sta caricando a {w} W.",
    hBattOut: "Batteria al {p} %, sta dando {w} W alla casa.",
    hBattIdle: "Batteria al {p} %, a riposo.",
    hGridIn: "Adesso prendiamo {w} W dalla rete. {k} da stamattina.",
    hGridOut: "Adesso mandiamo {w} W alla rete. {k} da stamattina.",
    hGridIdle: "Adesso la rete non serve. Oggi abbiamo preso {k}.",
    hDay: "{d}: il sole ha prodotto {k}",
    hShare: "Oggi la casa ha usato {b}: {a} da sole e batteria",
    hGauge: "Circa {a} in batteria, su {b}",
    offline: "L'inverter non risponde in questo momento. I numeri tornano da soli.",
    setup: "Ancora niente da mostrare. In Home Assistant apri Impostazioni, Dashboard, Energia e aggiungi i pannelli solari con il loro sensore di potenza.",
    missing: "Non trovati:",
  },
  es: {
    pages: "Páginas",
    tabNow: "Ahora", tabToday: "Hoy", tabHistory: "Días pasados", tabDetails: "Info",
    until: "Da energía a la casa, alcanza hasta las {t} aprox.",
    untilSun: "Da energía a la casa, alcanza hasta que llegue el sol",
    saved: "Hoy unos {v} ahorrados", savedNone: "Hoy todavía nada ahorrado", earned: "{v} ganados vendiendo",
    ySaved: "ahorrados", savedLabel: "Ahorrado",
    sunUse: "Uso del sol hoy", usedAtHome: "Sol usado en casa", homeMadeShare: "Consumo cubierto por sol y batería",
    battMonth: "Batería", roundTrip: "Devuelto el mes pasado", cycles: "Ciclos completos el mes pasado",
    battIn: "Cargada en la batería", battOut: "Sacada de la batería",
    forecast: "Pronóstico", fToday: "Pronóstico para hoy", fSoFar: "Producido hasta ahora", fTomorrow: "Pronóstico para mañana",
    noForecast: "No hay ningún pronóstico solar vinculado en los ajustes de Energía",
    monthNumbers: "El mes en números", colThis: "este", colLast: "pasado",
    prices: "Precios", buy: "Comprada, por kWh", sell: "Vendida, por kWh", notSet: "sin definir",
    runOn: "La casa funciona con {a}",
    and: "{a} y {b}",
    src: { sun: "el sol", battery: "la batería", grid: "la red" },
    subGrid: "La red está echando una mano",
    subExport: "El sol que sobra va a la red",
    subCharge: "El sol que sobra está cargando la batería",
    subBattery: "La batería devuelve el sol que guardó",
    sun: "Sol", noSun: "Sin sol", battery: "Batería", home: "Casa", grid: "Red",
    empty: "Vacía", low: "Baja", good: "Bien", nearlyFull: "Casi llena", full: "Llena",
    noUseYet: "Hoy la casa todavía no ha usado nada",
    charging: "Cargándose con el sol", discharging: "Dando energía a la casa", resting: "En reposo",
    adviceTitle: "Consejo",
    adviceGo: [
      "Buen momento para poner la lavadora o el lavavajillas",
      "Sol de sobra: buen momento para encender el horno",
      "Sobra sol: adelante con el lavavajillas",
      "El sol está generoso: buen momento para planchar",
      "Sol de sobra: buen momento para pasar la aspiradora",
      "Más sol del que necesita la casa: hora de lavar la ropa",
      "Sol que sobra: pon a cargar los teléfonos y las tabletas",
      "Mucho sol ahora: buen momento para la secadora",
      "Invita el sol: pon ahora los aparatos grandes",
      "Sobra sol en el techo: ¿horneamos algo?",
    ],
    adviceGoFull: [
      "Batería llena y sol de sobra: úsalo sin miedo",
      "Al sol ya no le queda sitio: enciende algo grande",
      "Batería llena y pleno sol: hora de la lavadora",
      "La batería está llena, el resto es un regalo: úsalo",
    ],
    adviceLow: [
      "Batería baja: los aparatos grandes usarán la red",
      "Batería casi vacía: deja los aparatos grandes para luego",
      "Poca batería y nada de sol: la ropa puede esperar",
      "La batería se agota: con calma hasta que vuelva el sol",
      "Queda poco en la batería: lo grande puede esperar",
    ],
    adviceEmpty: [
      "Batería vacía: por ahora la casa va con la red",
      "No queda nada en la batería, el sol la llenará",
      "Batería vacía: para lo grande, mejor esperar al sol",
    ],
    adviceWait: [
      "Hoy poco sol, mañana más: mejor lava mañana",
      "Sol perezoso hoy, mañana se anima: la ropa puede esperar",
      "Mañana viene más sol: deja los lavados grandes para mañana",
      "Hoy gris, mañana mejor: lavar puede esperar",
      "Hoy hay poco sol. El día de lavar es mañana",
    ],
    adviceOk: [
      "Todo bien, no hay nada que hacer",
      "Aquí todo tranquilo. ¿Hora de un café?",
      "Nada que hacer, la casa se cuida sola",
      "Todo va sobre ruedas, sigue así",
      "El sol está arriba y la casa sigue a su ritmo",
      "Por ahora no hace falta hacer nada, disfruta del día",
      "Nada que contar, y eso es buena noticia",
      "La casa está bien. Puedes relajarte",
      "Aquí todo en orden, no tienes que hacer nada",
      "Mar en calma en casa, no hace falta ayuda",
      "La casa va de maravilla",
      "Sin noticias, buenas noticias: aquí todo bien",
    ],
    adviceOkNight: [
      "El sol terminó su turno, la casa sigue sola",
      "El sol se fue a dormir, aquí todo bien",
      "Todo bien, hasta el sol descansa",
      "Noche tranquila, la casa tiene lo que necesita",
      "Nada que hacer esta noche, que la disfrutes",
      "Aquí todo en calma. Nos vemos con el sol",
      "Buenas noches de parte de la casa, todo va bien",
      "Nada que hacer hasta que vuelva el sol",
    ],
    adviceOkFull: [
      "Batería bien llena, no hay nada que hacer",
      "Batería bien cargada: día tranquilo por delante",
      "La batería está bien cargada y todo va bien",
      "Aquí estamos llenos de energía. ¿Y tú?",
    ],
    adviceOkRefill: [
      "Batería baja, pero el sol ya se encarga",
      "El sol está recargando la batería, solo dale tiempo",
      "Batería baja, sol trabajando: no tienes que hacer nada",
    ],
    shareToday: "de la energía de hoy se hizo en casa",
    todayNumbers: "Hoy en números",
    made: "El sol produjo", used: "La casa usó", takenBatt: "Sacada de la batería", taken: "Tomada de la red", sent: "Enviada a la red",
    nothing: "nada", almostNothing: "casi nada",
    yesterday: "Ayer", homeMade: "hecha en casa",
    ySun: "sol", yHouse: "casa", yGrid: "de la red", ySent: "a la red",
    week: "El sol en los últimos 7 días",
    monthTitle: "Este mes y el mes pasado",
    thisMonth: "Este mes hasta ahora", lastMonth: "El mes pasado",
    more: "Más sol por día que el mes pasado",
    less: "Un poco menos de sol por día que el mes pasado",
    same: "Más o menos el mismo sol que el mes pasado",
    loading: "Cargando...",
    hSun: "Los paneles están produciendo {w} W ahora. {k} en lo que va del día.",
    hSunOff: "Ahora no hay sol. Hoy los paneles produjeron {k}.",
    hHome: "La casa está usando {w} W ahora. {k} en lo que va del día.",
    hBattIn: "Batería al {p} %, cargándose a {w} W.",
    hBattOut: "Batería al {p} %, dando {w} W a la casa.",
    hBattIdle: "Batería al {p} %, en reposo.",
    hGridIn: "Ahora tomamos {w} W de la red. {k} en lo que va del día.",
    hGridOut: "Ahora enviamos {w} W a la red. {k} en lo que va del día.",
    hGridIdle: "Ahora no usamos la red. Hoy tomamos {k}.",
    hDay: "{d}: el sol produjo {k}",
    hShare: "Hoy la casa usó {b}: {a} del sol y la batería",
    hGauge: "Unos {a} en la batería, de {b}",
    offline: "El inversor no responde en este momento. Los números volverán solos.",
    setup: "Todavía no hay nada que mostrar. En Home Assistant abre Ajustes, Paneles de control, Energía y añade los paneles solares con su sensor de potencia.",
    missing: "No encontrados:",
  },
  fr: {
    pages: "Pages",
    tabNow: "Direct", tabToday: "Aujourd'hui", tabHistory: "Avant", tabDetails: "Infos",
    until: "Alimente la maison, de quoi tenir jusque vers {t}",
    untilSun: "Alimente la maison, de quoi tenir jusqu'au retour du soleil",
    saved: "Environ {v} économisés aujourd'hui", savedNone: "Rien d'économisé pour l'instant aujourd'hui", earned: "{v} gagnés en vendant",
    ySaved: "économisés", savedLabel: "Économisé",
    sunUse: "Usage du soleil aujourd'hui", usedAtHome: "Soleil utilisé à la maison", homeMadeShare: "Consommation couverte par soleil et batterie",
    battMonth: "Batterie", roundTrip: "Rendu le mois dernier", cycles: "Cycles complets le mois dernier",
    battIn: "Mis dans la batterie", battOut: "Pris dans la batterie",
    forecast: "Prévision", fToday: "Prévision pour aujourd'hui", fSoFar: "Produit jusqu'ici", fTomorrow: "Prévision pour demain",
    noForecast: "Aucune prévision solaire n'est reliée dans les réglages Énergie",
    monthNumbers: "Le mois en chiffres", colThis: "ce mois", colLast: "dernier",
    prices: "Prix", buy: "Acheté, par kWh", sell: "Vendu, par kWh", notSet: "non défini",
    runOn: "Le courant vient {a}",
    and: "{a} et {b}",
    src: { sun: "du soleil", battery: "de la batterie", grid: "du réseau" },
    subGrid: "Le réseau donne un coup de main",
    subExport: "Le soleil en trop part vers le réseau",
    subCharge: "Le soleil en trop remplit la batterie",
    subBattery: "La batterie rend le soleil mis de côté",
    sun: "Soleil", noSun: "Sans soleil", battery: "Batterie", home: "Maison", grid: "Réseau",
    empty: "Vide", low: "Faible", good: "Bien", nearlyFull: "Presque pleine", full: "Pleine",
    noUseYet: "La maison n'a encore rien consommé aujourd'hui",
    charging: "Se remplit de soleil", discharging: "Alimente la maison", resting: "Au repos",
    adviceTitle: "Conseil",
    adviceGo: [
      "Bon moment pour lancer une lessive ou le lave-vaisselle",
      "Plein de soleil : bon moment pour allumer le four",
      "Il reste du soleil : en route, le lave-vaisselle",
      "Le soleil est généreux : bon moment pour repasser",
      "Du soleil en trop : c'est le moment de l'aspirateur",
      "Plus de soleil qu'il n'en faut : l'heure de la lessive",
      "Du soleil en trop : recharge téléphones et tablettes",
      "Beaucoup de soleil : bon moment pour le sèche-linge",
      "C'est le soleil qui régale : lance les gros appareils",
      "Soleil en trop sur le toit : on enfourne quelque chose ?",
    ],
    adviceGoFull: [
      "Batterie pleine et soleil en trop : profites-en",
      "Le soleil ne sait plus où aller : allume quelque chose",
      "Batterie pleine, plein soleil : place à la lessive",
      "La batterie est pleine, le reste est cadeau : profites-en",
    ],
    adviceLow: [
      "Batterie faible : les gros appareils iront sur le réseau",
      "Batterie presque vide : les gros appareils, plus tard",
      "Peu de batterie, pas de soleil : la lessive attendra",
      "La batterie fatigue : doucement jusqu'au retour du soleil",
      "Batterie presque à sec : les gros travaux attendront",
    ],
    adviceEmpty: [
      "Batterie vide : pour l'instant, tout vient du réseau",
      "Plus rien dans la batterie, le soleil la remplira",
      "Batterie vide : pour les gros travaux, attends le soleil",
    ],
    adviceWait: [
      "Peu de soleil aujourd'hui, plus demain : lave demain",
      "Soleil paresseux, mieux demain : la lessive attendra",
      "Plus de soleil demain : les grosses lessives attendront",
      "Gris aujourd'hui, plus clair demain : laver peut attendre",
      "Peu de soleil aujourd'hui. Jour de lessive : demain",
    ],
    adviceOk: [
      "Tout va bien, rien à faire",
      "Tout est calme ici. Un petit café ?",
      "Rien à faire, la maison se débrouille toute seule",
      "Tout roule, continue comme ça",
      "Le soleil est levé, la maison suit son train-train",
      "Rien à faire pour l'instant, profite de ta journée",
      "Rien à signaler, et c'est une bonne nouvelle",
      "La maison va bien. Tu peux souffler",
      "Tout est en ordre ici, tu n'as rien à faire",
      "Calme plat à la maison, pas besoin d'aide",
      "La maison ronronne gentiment",
      "Pas de nouvelles, bonnes nouvelles : tout va bien ici",
    ],
    adviceOkNight: [
      "Le soleil a fini sa journée, la maison continue seule",
      "Le soleil est allé se coucher, tout va bien ici",
      "Tout va bien, même le soleil se repose",
      "Nuit tranquille, la maison a tout ce qu'il lui faut",
      "Rien à faire ce soir, passe une bonne soirée",
      "Tout est calme ici. On se retrouve avec le soleil",
      "La maison te dit bonne nuit, tout va bien",
      "Rien à faire jusqu'au retour du soleil",
    ],
    adviceOkFull: [
      "Batterie bien pleine, rien à faire",
      "Batterie bien remplie : une journée tranquille en vue",
      "La batterie est bien remplie et tout va bien",
      "Ici, on est pleins d'énergie. Et toi ?",
    ],
    adviceOkRefill: [
      "Batterie faible, mais le soleil s'en occupe déjà",
      "Le soleil recharge la batterie, laisse-lui le temps",
      "Batterie faible, soleil au travail : rien à faire",
    ],
    shareToday: "du courant d'aujourd'hui est fait maison",
    todayNumbers: "Aujourd'hui en chiffres",
    made: "Le soleil a produit", used: "La maison a utilisé", takenBatt: "Pris dans la batterie", taken: "Pris sur le réseau", sent: "Envoyé au réseau",
    nothing: "rien", almostNothing: "presque rien",
    yesterday: "Hier", homeMade: "fait maison",
    ySun: "soleil", yHouse: "maison", yGrid: "du réseau", ySent: "au réseau",
    week: "Le soleil des 7 derniers jours",
    monthTitle: "Ce mois-ci et le mois dernier",
    thisMonth: "Depuis le début du mois", lastMonth: "Le mois dernier",
    more: "Plus de soleil par jour que le mois dernier",
    less: "Un peu moins de soleil par jour que le mois dernier",
    same: "À peu près autant de soleil que le mois dernier",
    loading: "Chargement...",
    hSun: "Les panneaux produisent {w} W en ce moment. {k} depuis ce matin.",
    hSunOff: "Pas de soleil en ce moment. Les panneaux ont produit {k} aujourd'hui.",
    hHome: "La maison utilise {w} W en ce moment. {k} depuis ce matin.",
    hBattIn: "Batterie à {p} %, se remplit à {w} W.",
    hBattOut: "Batterie à {p} %, donne {w} W à la maison.",
    hBattIdle: "Batterie à {p} %, au repos.",
    hGridIn: "On prend {w} W sur le réseau en ce moment. {k} depuis ce matin.",
    hGridOut: "On envoie {w} W au réseau en ce moment. {k} depuis ce matin.",
    hGridIdle: "Pas besoin du réseau en ce moment. {k} pris aujourd'hui.",
    hDay: "{d} : le soleil a produit {k}",
    hShare: "Aujourd'hui la maison a utilisé {b}, dont {a} venus du soleil et de la batterie",
    hGauge: "Environ {a} dans la batterie, sur {b}",
    offline: "L'onduleur ne répond pas pour le moment. Les chiffres reviendront tout seuls.",
    setup: "Rien à afficher pour l'instant. Dans Home Assistant, ouvre Paramètres, Tableaux de bord, Énergie et ajoute les panneaux solaires avec leur capteur de puissance.",
    missing: "Introuvables :",
  },
  de: {
    pages: "Seiten",
    tabNow: "Jetzt", tabToday: "Heute", tabHistory: "Letzte Tage", tabDetails: "Info",
    until: "Versorgt das Haus, reicht bis etwa {t} Uhr",
    untilSun: "Versorgt das Haus, reicht, bis die Sonne übernimmt",
    saved: "Heute etwa {v} gespart", savedNone: "Heute noch nichts gespart", earned: "{v} durch Verkauf verdient",
    ySaved: "gespart", savedLabel: "Gespart",
    sunUse: "Sonnennutzung heute", usedAtHome: "Sonne im Haus genutzt", homeMadeShare: "Verbrauch aus Sonne und Batterie",
    battMonth: "Batterie", roundTrip: "Zurückgegeben im letzten Monat", cycles: "Volle Zyklen im letzten Monat",
    battIn: "In die Batterie", battOut: "Aus der Batterie",
    forecast: "Vorhersage", fToday: "Vorhersage für heute", fSoFar: "Bisher erzeugt", fTomorrow: "Vorhersage für morgen",
    noForecast: "In den Energie-Einstellungen ist keine Solarvorhersage verknüpft",
    monthNumbers: "Der Monat in Zahlen", colThis: "dieser", colLast: "letzter",
    prices: "Preise", buy: "Gekauft, pro kWh", sell: "Verkauft, pro kWh", notSet: "nicht festgelegt",
    runOn: "Strom {a}",
    and: "{a} und {b}",
    src: { sun: "von der Sonne", battery: "aus der Batterie", grid: "aus dem Netz" },
    subGrid: "Das Netz hilft ein wenig mit",
    subExport: "Die übrige Sonne geht ins Netz",
    subCharge: "Die übrige Sonne füllt die Batterie",
    subBattery: "Die Batterie gibt die gesparte Sonne zurück",
    sun: "Sonne", noSun: "Keine Sonne", battery: "Batterie", home: "Haus", grid: "Netz",
    empty: "Leer", low: "Niedrig", good: "Gut", nearlyFull: "Fast voll", full: "Voll",
    noUseYet: "Das Haus hat heute noch nichts verbraucht",
    charging: "Füllt sich mit Sonne", discharging: "Versorgt das Haus", resting: "Ruht sich aus",
    adviceTitle: "Tipp",
    adviceGo: [
      "Guter Moment für Wasch- oder Spülmaschine",
      "Viel Sonne: gute Zeit, den Backofen anzumachen",
      "Es ist Sonne übrig: los mit der Spülmaschine",
      "Die Sonne ist großzügig: gute Zeit zum Bügeln",
      "Sonne übrig: ein guter Moment für den Staubsauger",
      "Mehr Sonne, als das Haus braucht: Zeit für die Wäsche",
      "Sonne im Überfluss: Lade Handys und Tablets auf",
      "Gerade viel Sonne: gute Zeit für den Trockner",
      "Die Sonne zahlt: Lass jetzt die großen Geräte laufen",
      "Sonne übrig auf dem Dach: Zeit, etwas zu backen?",
    ],
    adviceGoFull: [
      "Batterie voll und Sonne übrig: Nutz sie ruhig",
      "Die Sonne weiß nicht mehr wohin: Schalte etwas Großes ein",
      "Volle Batterie, volle Sonne: Zeit für die Waschmaschine",
      "Die Batterie ist voll, der Rest ist geschenkt: Nutz ihn",
    ],
    adviceLow: [
      "Batterie niedrig: Große Geräte laufen jetzt übers Netz",
      "Batterie fast leer: Große Geräte lieber später anmachen",
      "Wenig Batterie, keine Sonne: Die Wäsche kann warten",
      "Die Batterie geht zur Neige: Sachte, bis die Sonne kommt",
      "Nur noch wenig in der Batterie: Großes kann warten",
    ],
    adviceEmpty: [
      "Batterie leer: Das Haus läuft vorerst übers Netz",
      "Nichts mehr in der Batterie, die Sonne füllt sie wieder",
      "Batterie leer: Mit Großem lieber auf die Sonne warten",
    ],
    adviceWait: [
      "Heute wenig Sonne, morgen mehr: Wasch lieber morgen",
      "Sonne heute faul, morgen fleißig: Die Wäsche kann warten",
      "Morgen mehr Sonne: Heb dir die große Wäsche auf",
      "Heute grau, morgen heller: Das Waschen kann warten",
      "Heute wenig Sonne. Waschtag ist morgen",
    ],
    adviceOk: [
      "Alles gut, nichts zu tun",
      "Hier ist alles ruhig. Zeit für einen Kaffee?",
      "Nichts zu tun, das Haus kümmert sich um sich selbst",
      "Alles läuft rund, mach einfach weiter",
      "Die Sonne ist da und das Haus läuft vor sich hin",
      "Gerade ist nichts zu tun, genieß deinen Tag",
      "Nichts zu melden, und das ist eine gute Nachricht",
      "Dem Haus geht es gut. Du kannst dich entspannen",
      "Hier ist alles in Ordnung, du musst nichts tun",
      "Alles im grünen Bereich zu Hause, keine Hilfe nötig",
      "Das Haus schnurrt zufrieden vor sich hin",
      "Keine Nachricht ist gute Nachricht: Hier ist alles gut",
    ],
    adviceOkNight: [
      "Die Sonne hat Feierabend, das Haus macht allein weiter",
      "Die Sonne ist schlafen gegangen, hier ist alles gut",
      "Alles gut, sogar die Sonne ruht sich aus",
      "Ruhige Nacht, das Haus hat alles, was es braucht",
      "Nichts zu tun heute Abend, genieß den Abend",
      "Hier ist alles ruhig. Wir sehen uns mit der Sonne",
      "Das Haus sagt gute Nacht, alles ist gut",
      "Nichts zu tun, bis die Sonne wiederkommt",
    ],
    adviceOkFull: [
      "Batterie schön voll, nichts zu tun",
      "Viel in der Batterie: Ein ruhiger Tag liegt vor dir",
      "Die Batterie ist gut gefüllt und alles ist in Ordnung",
      "Hier sind wir voller Energie. Und du?",
    ],
    adviceOkRefill: [
      "Batterie niedrig, aber die Sonne kümmert sich schon",
      "Die Sonne füllt die Batterie, gib ihr etwas Zeit",
      "Batterie niedrig, Sonne am Werk: Du musst nichts tun",
    ],
    shareToday: "vom heutigen Strom ist hausgemacht",
    todayNumbers: "Heute in Zahlen",
    made: "Von der Sonne erzeugt", used: "Vom Haus verbraucht", takenBatt: "Aus der Batterie", taken: "Aus dem Netz", sent: "Ins Netz",
    nothing: "nichts", almostNothing: "fast nichts",
    yesterday: "Gestern", homeMade: "hausgemacht",
    ySun: "Sonne", yHouse: "Haus", yGrid: "aus dem Netz", ySent: "ins Netz",
    week: "Die Sonne der letzten 7 Tage",
    monthTitle: "Dieser Monat und der letzte",
    thisMonth: "Dieser bisher", lastMonth: "Der letzte",
    more: "Mehr Sonne pro Tag als im letzten Monat",
    less: "Etwas weniger Sonne pro Tag als im letzten Monat",
    same: "Etwa gleich viel Sonne wie im letzten Monat",
    loading: "Lädt...",
    hSun: "Die Solarmodule erzeugen gerade {w} W. Heute bisher {k}.",
    hSunOff: "Gerade keine Sonne. Heute {k} erzeugt.",
    hHome: "Das Haus verbraucht gerade {w} W. Heute bisher {k}.",
    hBattIn: "Batterie bei {p} %, lädt mit {w} W.",
    hBattOut: "Batterie bei {p} %, gibt {w} W ans Haus.",
    hBattIdle: "Batterie bei {p} %, ruht sich aus.",
    hGridIn: "Wir holen gerade {w} W aus dem Netz. Heute bisher {k}.",
    hGridOut: "Wir schicken gerade {w} W ins Netz. Heute bisher {k}.",
    hGridIdle: "Wir brauchen das Netz gerade nicht. Heute {k} geholt.",
    hDay: "{d}: Die Sonne hat {k} erzeugt",
    hShare: "{a} von den heute verbrauchten {b} kamen von eigener Sonne und Batterie",
    hGauge: "Etwa {a} in der Batterie, von {b}",
    offline: "Der Wechselrichter antwortet gerade nicht. Die Zahlen kommen von selbst zurück.",
    setup: "Noch nichts zu zeigen. Öffne in Home Assistant Einstellungen, Dashboards, Energie und füge die Solarmodule mit ihrem Leistungssensor hinzu.",
    missing: "Nicht gefunden:",
  },
  pt: {
    pages: "Páginas",
    tabNow: "Agora", tabToday: "Hoje", tabHistory: "Últimos dias", tabDetails: "Info",
    until: "Alimentando a casa, dá até por volta das {t}",
    untilSun: "Alimentando a casa, dá até o sol chegar",
    saved: "Cerca de {v} economizados hoje", savedNone: "Ainda nada economizado hoje", earned: "{v} ganhos com a venda",
    ySaved: "economizados", savedLabel: "Economizado",
    sunUse: "Uso do sol hoje", usedAtHome: "Sol usado em casa", homeMadeShare: "Consumo coberto por sol e bateria",
    battMonth: "Bateria", roundTrip: "Devolvido no mês passado", cycles: "Ciclos completos no mês passado",
    battIn: "Guardada na bateria", battOut: "Tirada da bateria",
    forecast: "Previsão", fToday: "Previsão para hoje", fSoFar: "Produzido até agora", fTomorrow: "Previsão para amanhã",
    noForecast: "Nenhuma previsão solar ligada nas configurações de Energia",
    monthNumbers: "O mês em números", colThis: "este", colLast: "passado",
    prices: "Preços", buy: "Comprada, por kWh", sell: "Vendida, por kWh", notSet: "não definido",
    runOn: "Agora a energia vem {a}",
    and: "{a} e {b}",
    src: { sun: "do sol", battery: "da bateria", grid: "da rede" },
    subGrid: "A rede dá uma mãozinha",
    subExport: "O sol que sobra vai para a rede",
    subCharge: "O sol que sobra carrega a bateria",
    subBattery: "A bateria devolve o sol que guardou",
    sun: "Sol", noSun: "Sem sol", battery: "Bateria", home: "Casa", grid: "Rede",
    empty: "Vazia", low: "Baixa", good: "Bem", nearlyFull: "Quase cheia", full: "Cheia",
    noUseYet: "Hoje a casa ainda não usou nada",
    charging: "Carregando com o sol", discharging: "Alimentando a casa", resting: "Em repouso",
    adviceTitle: "Dica",
    adviceGo: [
      "Boa hora para a máquina de lavar ou a lava-louças",
      "Sol de sobra: boa hora para ligar o forno",
      "Sobra sol: pode ligar a lava-louças",
      "O sol está generoso: boa hora para passar roupa",
      "Sol de sobra: bom momento para o aspirador",
      "Mais sol do que a casa precisa: hora de lavar roupa",
      "Sol que sobra: ponha celulares e tablets para carregar",
      "Muito sol agora: boa hora para a secadora",
      "O sol paga a conta: ligue agora os aparelhos grandes",
      "Sol de sobra no telhado: que tal assar alguma coisa?",
    ],
    adviceGoFull: [
      "Bateria cheia e sol de sobra: use à vontade",
      "O sol não tem mais onde ficar: ligue algo grande",
      "Bateria cheia, sol pleno: hora da máquina de lavar",
      "A bateria está cheia, o resto é presente: aproveite",
    ],
    adviceLow: [
      "Bateria baixa: aparelhos grandes vão usar a rede",
      "Bateria quase vazia: deixe os aparelhos grandes para depois",
      "Pouca bateria e nada de sol: a roupa pode esperar",
      "Bateria no fim: vá com calma até o sol voltar",
      "Resta pouco na bateria: o que é grande pode esperar",
    ],
    adviceEmpty: [
      "Bateria vazia: por enquanto a casa usa a rede",
      "Nada na bateria, o sol vai encher de novo",
      "Bateria vazia: para o que é grande, espere o sol",
    ],
    adviceWait: [
      "Pouco sol hoje, mais amanhã: melhor lavar amanhã",
      "Sol preguiçoso hoje, amanhã melhora: a roupa pode esperar",
      "Amanhã vem mais sol: deixe as grandes lavagens para amanhã",
      "Hoje cinzento, amanhã melhor: lavar pode esperar",
      "Pouco sol hoje. O dia de lavar roupa é amanhã",
    ],
    adviceOk: [
      "Tudo certo, nada a fazer",
      "Tudo calmo por aqui. Que tal um café?",
      "Nada a fazer, a casa cuida de si mesma",
      "Tudo corre bem, pode continuar",
      "O sol está no céu e a casa segue tranquila",
      "Nada para fazer agora, aproveite o dia",
      "Nada a contar, e isso é uma boa notícia",
      "A casa está bem. Pode relaxar",
      "Tudo em ordem por aqui, não precisa fazer nada",
      "Mar calmo em casa, não é preciso ajuda",
      "A casa vai às mil maravilhas",
      "Sem notícias, boas notícias: tudo bem por aqui",
    ],
    adviceOkNight: [
      "O sol encerrou o expediente, a casa segue sozinha",
      "O sol foi dormir, tudo bem por aqui",
      "Tudo certo, até o sol descansa",
      "Noite tranquila, a casa tem tudo o que precisa",
      "Nada a fazer esta noite, aproveite para descansar",
      "Tudo calmo por aqui. Até amanhã, com o sol",
      "A casa deseja boa noite, está tudo bem",
      "Nada a fazer até o sol voltar",
    ],
    adviceOkFull: [
      "Bateria bem cheia, nada a fazer",
      "Bateria bem carregada: um dia tranquilo pela frente",
      "A bateria está bem carregada e tudo vai bem",
      "Aqui estamos cheios de energia. E você?",
    ],
    adviceOkRefill: [
      "Bateria baixa, mas o sol já cuida disso",
      "O sol recarrega a bateria, é só dar um tempo",
      "Bateria baixa, sol em ação: nada para você fazer",
    ],
    shareToday: "da energia de hoje foi feita em casa",
    todayNumbers: "Hoje em números",
    made: "O sol produziu", used: "A casa usou", takenBatt: "Tirada da bateria", taken: "Tirada da rede", sent: "Enviada para a rede",
    nothing: "nada", almostNothing: "quase nada",
    yesterday: "Ontem", homeMade: "feita em casa",
    ySun: "sol", yHouse: "casa", yGrid: "da rede", ySent: "para a rede",
    week: "O sol nos últimos 7 dias",
    monthTitle: "Este mês e o mês passado",
    thisMonth: "Este mês até agora", lastMonth: "Mês passado",
    more: "Mais sol por dia do que no mês passado",
    less: "Um pouco menos de sol por dia do que no mês passado",
    same: "Mais ou menos o mesmo sol do mês passado",
    loading: "Carregando...",
    hSun: "Os painéis produzem {w} W agora. {k} hoje até agora.",
    hSunOff: "Sem sol agora. Hoje os painéis produziram {k}.",
    hHome: "A casa usa {w} W agora. {k} hoje até agora.",
    hBattIn: "Bateria em {p} %, carregando a {w} W.",
    hBattOut: "Bateria em {p} %, dando {w} W para a casa.",
    hBattIdle: "Bateria em {p} %, em repouso.",
    hGridIn: "Agora tiramos {w} W da rede. {k} hoje até agora.",
    hGridOut: "Agora enviamos {w} W para a rede. {k} hoje até agora.",
    hGridIdle: "Agora não usamos a rede. Hoje tiramos {k}.",
    hDay: "{d}: o sol produziu {k}",
    hShare: "Hoje a casa usou {b}: {a} vieram do sol e da bateria",
    hGauge: "Cerca de {a} na bateria, de {b}",
    offline: "O inversor não responde no momento. Os números voltam sozinhos.",
    setup: "Ainda não há nada para mostrar. No Home Assistant, abra Configurações, Painéis, Energia e adicione os painéis solares com o sensor de potência deles.",
    missing: "Não encontrados:",
  },
  nl: {
    pages: "Pagina's",
    tabNow: "Nu", tabToday: "Vandaag", tabHistory: "Vorige dagen", tabDetails: "Info",
    until: "Geeft het huis stroom, genoeg tot ongeveer {t}",
    untilSun: "Geeft het huis stroom, genoeg tot de zon het overneemt",
    saved: "Vandaag ongeveer {v} bespaard", savedNone: "Vandaag nog niets bespaard", earned: "{v} verdiend met verkopen",
    ySaved: "bespaard", savedLabel: "Bespaard",
    sunUse: "Zongebruik vandaag", usedAtHome: "Zon gebruikt in huis", homeMadeShare: "Verbruik gedekt door zon en batterij",
    battMonth: "Batterij", roundTrip: "Teruggegeven vorige maand", cycles: "Volle cycli vorige maand",
    battIn: "In de batterij gestopt", battOut: "Uit de batterij gehaald",
    forecast: "Verwachting", fToday: "Verwachting voor vandaag", fSoFar: "Tot nu toe opgewekt", fTomorrow: "Verwachting voor morgen",
    noForecast: "Er is geen zonneverwachting gekoppeld in de Energie-instellingen",
    monthNumbers: "De maand in cijfers", colThis: "deze", colLast: "vorige",
    prices: "Prijzen", buy: "Gekocht, per kWh", sell: "Verkocht, per kWh", notSet: "niet ingesteld",
    runOn: "De stroom komt nu {a}",
    and: "{a} en {b}",
    src: { sun: "van de zon", battery: "uit de batterij", grid: "van het net" },
    subGrid: "Het net helpt een handje",
    subExport: "De extra zon gaat naar het net",
    subCharge: "De extra zon vult de batterij",
    subBattery: "De batterij geeft de bewaarde zon terug",
    sun: "Zon", noSun: "Geen zon", battery: "Batterij", home: "Huis", grid: "Net",
    empty: "Leeg", low: "Laag", good: "Goed", nearlyFull: "Bijna vol", full: "Vol",
    noUseYet: "Het huis heeft vandaag nog niets verbruikt",
    charging: "Vult zich met zon", discharging: "Geeft het huis stroom", resting: "Rust uit",
    adviceTitle: "Tip",
    adviceGo: [
      "Goed moment voor de wasmachine of de vaatwasser",
      "Volop zon: goed moment om de oven aan te zetten",
      "Er is zon over: zet de vaatwasser maar aan",
      "De zon is gul: goed moment om te strijken",
      "Zon over: een mooi moment voor de stofzuiger",
      "Meer zon dan het huis nodig heeft: tijd voor de was",
      "Zon genoeg over: laad de telefoons en tablets op",
      "Veel zon nu: goed moment voor de droger",
      "De zon trakteert: zet nu de grote apparaten aan",
      "Zon over op het dak: tijd om iets te bakken?",
    ],
    adviceGoFull: [
      "Batterij vol en zon over: gebruik het gerust",
      "De zon kan nergens meer heen: zet iets groots aan",
      "Volle batterij, volle zon: tijd voor de wasmachine",
      "De batterij is vol, de rest is cadeau: gebruik het",
    ],
    adviceLow: [
      "Batterij laag: grote apparaten gebruiken nu het net",
      "Batterij bijna leeg: bewaar de grote apparaten voor later",
      "Lage batterij en geen zon: de was kan wachten",
      "Batterij raakt leeg: doe rustig aan tot de zon terug is",
      "Nog weinig in de batterij: grote klussen kunnen wachten",
    ],
    adviceEmpty: [
      "Batterij leeg: het huis draait nu even op het net",
      "Niets meer in de batterij, de zon vult die weer bij",
      "Lege batterij: wacht met grote klussen op de zon",
    ],
    adviceWait: [
      "Weinig zon vandaag, morgen meer: was liever morgen",
      "Luie zon vandaag, morgen drukker: de was kan wachten",
      "Morgen komt er meer zon: bewaar de grote was tot dan",
      "Vandaag grijs, morgen lichter: wassen kan wachten",
      "Weinig zon vandaag. Wasdag is morgen",
    ],
    adviceOk: [
      "Alles goed, niets te doen",
      "Alles rustig hier. Tijd voor koffie?",
      "Niets te doen, het huis zorgt voor zichzelf",
      "Alles loopt op rolletjes, ga zo door",
      "De zon is op en het huis draait lekker door",
      "Er hoeft nu niets, geniet van je dag",
      "Niets te melden, en dat is goed nieuws",
      "Het huis maakt het goed. Je kunt ontspannen",
      "Alles in orde hier, jij hoeft niets te doen",
      "Het huis zit in rustig vaarwater, geen hulp nodig",
      "Het huis snort tevreden verder",
      "Geen nieuws is goed nieuws: alles prima hier",
    ],
    adviceOkNight: [
      "De zon heeft vrij, het huis redt zich alleen",
      "De zon is naar bed, alles is goed hier",
      "Alles goed, zelfs de zon rust even uit",
      "Rustige nacht, het huis heeft alles wat het nodig heeft",
      "Niets te doen vanavond, geniet van je avond",
      "Alles kalm hier. We zien je weer met de zon",
      "Welterusten van het huis, alles is goed",
      "Niets te doen tot de zon terugkomt",
    ],
    adviceOkFull: [
      "Batterij lekker vol, niets te doen",
      "Genoeg in de batterij: een rustige dag voor de boeg",
      "De batterij is bijgevuld en alles is goed",
      "Vol energie hier. En jij?",
    ],
    adviceOkRefill: [
      "Batterij is laag, maar de zon is er al mee bezig",
      "De zon vult de batterij bij, geef het even tijd",
      "Lage batterij, zon aan het werk: jij hoeft niets te doen",
    ],
    shareToday: "van de stroom van vandaag is zelf opgewekt",
    todayNumbers: "Vandaag in cijfers",
    made: "De zon maakte", used: "Het huis gebruikte", takenBatt: "Uit de batterij gehaald", taken: "Van het net gehaald", sent: "Naar het net gestuurd",
    nothing: "niets", almostNothing: "bijna niets",
    yesterday: "Gisteren", homeMade: "zelf opgewekt",
    ySun: "zon", yHouse: "huis", yGrid: "van het net", ySent: "naar het net",
    week: "De zon in de laatste 7 dagen",
    monthTitle: "Deze maand en vorige maand",
    thisMonth: "Deze maand tot nu toe", lastMonth: "Vorige maand",
    more: "Meer zon per dag dan vorige maand",
    less: "Iets minder zon per dag dan vorige maand",
    same: "Ongeveer evenveel zon als vorige maand",
    loading: "Laden...",
    hSun: "De panelen maken nu {w} W. Vandaag tot nu toe {k}.",
    hSunOff: "Nu geen zon. Vandaag {k} gemaakt.",
    hHome: "Het huis gebruikt nu {w} W. Vandaag tot nu toe {k}.",
    hBattIn: "Batterij op {p} %, vult zich met {w} W.",
    hBattOut: "Batterij op {p} %, geeft {w} W aan het huis.",
    hBattIdle: "Batterij op {p} %, rust uit.",
    hGridIn: "We halen nu {w} W van het net. Vandaag tot nu toe {k}.",
    hGridOut: "We sturen nu {w} W naar het net. Vandaag tot nu toe {k}.",
    hGridIdle: "We gebruiken het net nu niet. Vandaag {k} gehaald.",
    hDay: "{d}: de zon maakte {k}",
    hShare: "{a} van de {b} die vandaag gebruikt is, kwam van onze eigen zon en batterij",
    hGauge: "Ongeveer {a} in de batterij, van de {b}",
    offline: "De omvormer reageert nu even niet. De cijfers komen vanzelf terug.",
    setup: "Nog niets te tonen. Open in Home Assistant Instellingen, Dashboards, Energie en voeg de zonnepanelen toe met hun vermogenssensor.",
    missing: "Niet gevonden:",
  },
  pl: {
    pages: "Strony",
    tabNow: "Teraz", tabToday: "Dzisiaj", tabHistory: "Minione dni", tabDetails: "Info",
    until: "Zasila dom, wystarczy mniej więcej do {t}",
    untilSun: "Zasila dom, wystarczy, aż zaświeci słońce",
    saved: "Dziś zaoszczędzono około {v}", savedNone: "Dziś jeszcze nic nie zaoszczędzono", earned: "{v} ze sprzedaży",
    ySaved: "oszczędności", savedLabel: "Oszczędności",
    sunUse: "Wykorzystanie słońca dziś", usedAtHome: "Słońce zużyte w domu", homeMadeShare: "Zużycie pokryte słońcem i baterią",
    battMonth: "Bateria", roundTrip: "Oddane w zeszłym miesiącu", cycles: "Pełne cykle w zeszłym miesiącu",
    battIn: "Bateria przyjęła", battOut: "Bateria oddała",
    forecast: "Prognoza", fToday: "Prognoza na dziś", fSoFar: "Wyprodukowano dotąd", fTomorrow: "Prognoza na jutro",
    noForecast: "W ustawieniach Energii nie podłączono prognozy słońca",
    monthNumbers: "Miesiąc w liczbach", colThis: "ten", colLast: "zeszły",
    prices: "Ceny", buy: "Kupno, za kWh", sell: "Sprzedaż, za kWh", notSet: "nie ustawiono",
    runOn: "Prąd płynie teraz {a}",
    and: "{a} i {b}",
    src: { sun: "ze słońca", battery: "z baterii", grid: "z sieci" },
    subGrid: "Sieć trochę pomaga",
    subExport: "Nadmiar słońca idzie do sieci",
    subCharge: "Nadmiar słońca ładuje baterię",
    subBattery: "Bateria oddaje słońce, które odłożyła",
    sun: "Słońce", noSun: "Bez słońca", battery: "Bateria", home: "Dom", grid: "Sieć",
    empty: "Pusta", low: "Słaba", good: "Dobrze", nearlyFull: "Prawie pełna", full: "Pełna",
    noUseYet: "Dom jeszcze dziś niczego nie zużył",
    charging: "Ładuje się słońcem", discharging: "Zasila dom", resting: "Odpoczywa",
    adviceTitle: "Porada",
    adviceGo: [
      "Dobra chwila, żeby włączyć pralkę albo zmywarkę",
      "Dużo słońca: dobra pora, żeby włączyć piekarnik",
      "Słońca zostaje: śmiało włączaj zmywarkę",
      "Słońce jest hojne: dobra pora na prasowanie",
      "Słońca w nadmiarze: dobra chwila na odkurzanie",
      "Więcej słońca, niż dom potrzebuje: czas na pranie",
      "Słońca pod dostatkiem: naładuj telefony i tablety",
      "Teraz dużo słońca: dobra pora na suszarkę",
      "Słońce stawia: włącz teraz duże urządzenia",
      "Nadmiar słońca na dachu: może coś upiec?",
    ],
    adviceGoFull: [
      "Bateria pełna, a słońca wciąż dużo: korzystaj śmiało",
      "Słońca nie ma już gdzie schować: włącz coś dużego",
      "Pełna bateria, pełne słońce: czas na pralkę",
      "Bateria pełna, reszta to prezent: korzystaj",
    ],
    adviceLow: [
      "Słaba bateria: duże urządzenia wezmą prąd z sieci",
      "Bateria prawie pusta: duże urządzenia zostaw na później",
      "Słaba bateria i brak słońca: pranie może poczekać",
      "Bateria się kończy: oszczędzaj, aż wróci słońce",
      "W baterii zostało niewiele: duże prace mogą poczekać",
    ],
    adviceEmpty: [
      "Bateria pusta: na razie dom korzysta z sieci",
      "W baterii nic nie zostało, słońce ją napełni",
      "Pusta bateria: z dużymi pracami poczekaj na słońce",
    ],
    adviceWait: [
      "Dziś mało słońca, jutro więcej: lepiej prać jutro",
      "Dziś słońce leniwe, jutro żwawsze: pranie może poczekać",
      "Jutro będzie więcej słońca: duże prania zostaw na jutro",
      "Dziś szaro, jutro jaśniej: z praniem można poczekać",
      "Dziś mało słońca. Dzień prania jest jutro",
    ],
    adviceOk: [
      "Wszystko dobrze, nic nie trzeba robić",
      "Tu wszystko spokojnie. Może kawa?",
      "Nic do roboty, dom sam o siebie dba",
      "Wszystko idzie gładko, tak trzymaj",
      "Słońce wstało, a dom spokojnie pracuje",
      "Teraz nic nie trzeba robić, miłego dnia",
      "Nic do zgłoszenia, i to dobra wiadomość",
      "Dom ma się dobrze. Możesz odpocząć",
      "Tu wszystko w porządku, nic nie musisz robić",
      "W domu cisza jak makiem zasiał, pomoc niepotrzebna",
      "Dom działa jak w zegarku",
      "Brak wiadomości to dobra wiadomość: tu wszystko gra",
    ],
    adviceOkNight: [
      "Słońce skończyło zmianę, dom radzi sobie sam",
      "Słońce poszło spać, tu wszystko dobrze",
      "Wszystko dobrze, nawet słońce odpoczywa",
      "Spokojna noc, dom ma wszystko, czego potrzebuje",
      "Dziś wieczorem nic do roboty, miłego wieczoru",
      "Tu spokój. Do zobaczenia ze słońcem",
      "Dom mówi dobranoc, wszystko w porządku",
      "Nic do roboty, dopóki nie wróci słońce",
    ],
    adviceOkFull: [
      "Bateria ładnie pełna, nic nie trzeba robić",
      "W baterii dużo zapasu: zapowiada się spokojny dzień",
      "Bateria jest naładowana i wszystko gra",
      "Tu energii pod dostatkiem. A u ciebie?",
    ],
    adviceOkRefill: [
      "Słaba bateria, ale słońce już się nią zajmuje",
      "Słońce ładuje baterię, daj mu tylko trochę czasu",
      "Słaba bateria, słońce pracuje: nic nie musisz robić",
    ],
    shareToday: "dzisiejszego prądu było domowej roboty",
    todayNumbers: "Dzisiaj w liczbach",
    made: "Słońce dało", used: "Dom zużył", takenBatt: "Wzięte z baterii", taken: "Wzięte z sieci", sent: "Wysłane do sieci",
    nothing: "nic", almostNothing: "prawie nic",
    yesterday: "Wczoraj", homeMade: "domowej roboty",
    ySun: "słońce", yHouse: "dom", yGrid: "z sieci", ySent: "do sieci",
    week: "Słońce w ostatnich 7 dniach",
    monthTitle: "Ten miesiąc i zeszły miesiąc",
    thisMonth: "W tym miesiącu dotąd", lastMonth: "W zeszłym miesiącu",
    more: "Więcej słońca na dzień niż w zeszłym miesiącu",
    less: "Trochę mniej słońca na dzień niż w zeszłym miesiącu",
    same: "Mniej więcej tyle słońca co w zeszłym miesiącu",
    loading: "Ładowanie...",
    hSun: "Panele dają teraz {w} W. Dziś do tej pory {k}.",
    hSunOff: "Teraz nie ma słońca. Dziś panele dały {k}.",
    hHome: "Dom zużywa teraz {w} W. Dziś do tej pory {k}.",
    hBattIn: "Bateria ma {p} %, ładuje się z mocą {w} W.",
    hBattOut: "Bateria ma {p} %, oddaje domowi {w} W.",
    hBattIdle: "Bateria ma {p} %, odpoczywa.",
    hGridIn: "Bierzemy teraz {w} W z sieci. Dziś do tej pory {k}.",
    hGridOut: "Wysyłamy teraz {w} W do sieci. Dziś do tej pory {k}.",
    hGridIdle: "Teraz nie korzystamy z sieci. Dziś wzięliśmy {k}.",
    hDay: "{d}: słońce dało {k}",
    hShare: "Dom zużył dziś {b}, z tego {a} z własnego słońca i baterii",
    hGauge: "Około {a} w baterii, z {b}",
    offline: "Falownik teraz nie odpowiada. Liczby wrócą same.",
    setup: "Na razie nie ma co pokazać. W Home Assistant otwórz Ustawienia, Dashboardy, Energia i dodaj panele słoneczne z ich czujnikiem mocy.",
    missing: "Nie znaleziono:",
  },
};
